version: 1
services:
  - type: web
    name: my-telegram-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN  # Assuming you've set this in Render's dashboard
      - key: FIREBASE_SERVICE_ACCOUNT
        fromSecret: FIREBASE_SERVICE_ACCOUNT  # Assuming you've set this in Render's dashboard
    plan: free
